"""Central configuration for the AfyaPlus Multimodal Intake Assistant.

All paths and model names live here so every script (build_index, search,
caption_image, transcribe_audio, router, app, evaluate) agrees on them.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# --- Data locations ---------------------------------------------------------
IMAGES_INDEX_DIR = ROOT / "data" / "images" / "index"
IMAGES_TEST_DIR = ROOT / "data" / "images" / "test_cases"
AUDIO_DIR = ROOT / "data" / "audio"
OUTPUTS_DIR = ROOT / "outputs"
INDEX_EMBEDDINGS_PATH = OUTPUTS_DIR / "clip_index.npz"
INDEX_LABELS_PATH = IMAGES_INDEX_DIR / "labels.json"

# --- Model selection ---------------------------------------------------------
# This project runs entirely on local/open models (no API key, no cost) per
# the capstone's stated fallback path. See README "API vs local fallback".
CLIP_MODEL_NAME = "openai/clip-vit-base-patch32"
CAPTION_MODEL_NAME = "Salesforce/blip-image-captioning-base"  # open equivalent of GPT-4o vision
WHISPER_MODEL_SIZE = "base"  # faster-whisper model size (open equivalent of OpenAI Whisper API)
EXTRACTION_MODEL_NAME = "google/flan-t5-small"  # local instruction model for field extraction

# --- Retrieval threshold -----------------------------------------------------
# Chosen empirically via `python search.py --calibrate`, which measures CLIP
# cosine similarity for known-relevant vs known-irrelevant text queries
# against this index: irrelevant queries topped out at ~0.17, relevant
# queries bottomed out at ~0.21. 0.19 sits in that gap -- above the
# irrelevant ceiling, below the relevant floor -- so it filters off-topic
# queries without discarding true positives. Re-run --calibrate after adding
# or changing index images, since the gap is index-dependent.
MIN_SIMILARITY_THRESHOLD = 0.19

# --- Out-of-scope detection for captioning -----------------------------------
# Zero-shot CLIP labels used to decide whether an uploaded photo resembles
# anything in-domain at all (see caption_image._is_out_of_scope). Calibrated
# against this project's 17-image index + 3 test cases: real domain images
# scored 0.276-0.308 max similarity across these labels, the out-of-scope
# test photo (a car) scored 0.217, and the clear rash test photo scored
# 0.267. 0.24 sits in the gap between the out-of-scope photo and every real
# domain image, so it flags the former without blocking genuine cases.
DOMAIN_LABELS = [
    "a rash", "a bruise", "a burn", "a wound or cut", "swelling",
    "an insect bite", "hives", "red eye", "a mole or skin lesion",
    "an infection", "a foot ulcer", "skin discoloration",
]
OUT_OF_SCOPE_SIMILARITY_CEILING = 0.24

# --- Safety copy --------------------------------------------------------------
CAPTION_DISCLAIMER = (
    "This description is generated by an AI model for informational and "
    "operational triage purposes only. It is NOT a medical diagnosis. "
    "A qualified clinician must review this case before any care decision is made."
)
HUMAN_REVIEW_FLAG = "HUMAN_REVIEW_REQUIRED"
UNREADABLE_FLAG = "UNREADABLE"
OUT_OF_SCOPE_FLAG = "OUT_OF_SCOPE"

TRANSCRIPT_DISCLAIMER = (
    "This transcript and extracted fields are AI-generated from an audio "
    "recording and may contain errors. They support intake triage only and "
    "do not replace a clinician's assessment."
)
